version: 2.1

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      - run:
          name: lint code
          command: echo "Linting repository"

      - run:
          name: run unit tests
          command: echo "Running unit tests"

  continuous-delivery:
    docker:
      - image: google/cloud-sdk
    resource_class: medium
    environment:
      REPOSITORY: ner-bert
      IMAGE_NAME: ner-bert
      IMAGE_TAG: latest
    steps:
      - checkout
      - run:
          name: google cloud authentication
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: build and tag
          command: docker build -t $GOOGLE_COMPUTE_ZONE-docker.pkg.dev/${GOOGLE_PROJECT_ID}/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: configure docker login
          command: gcloud auth configure-docker $GOOGLE_COMPUTE_ZONE-docker.pkg.dev

      - run:
          name: push to private repository
          command: docker push $GOOGLE_COMPUTE_ZONE-docker.pkg.dev/${GOOGLE_PROJECT_ID}/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

  continuous-deployment:
    machine: true
    resource_class: deep-learning-01/dl-ineuron
    environment:
      REPOSITORY: ner-bert
      GAR_IMAGE_NAME: ner-bert
      IMAGE_TAG: latest
    steps:
      - checkout

      - run:
          name: Google Cloud Authentication
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Configure Docker Login
          command: gcloud auth configure-docker $GOOGLE_COMPUTE_ZONE-docker.pkg.dev

      - run:
          name: Pull image from Google Artifacts
          command: docker pull ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/$REPOSITORY/$GAR_IMAGE_NAME:$IMAGE_TA

      - run:
          name: Start Docker container
          command: docker compose up -d
          environment:
            IMAGE_NAME: ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/$REPOSITORY/$GAR_IMAGE_NAME:$IMAGE_TAG

      - run:
          name: free up system space
          command: docker system prune -f


workflows:
  CICD:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration

      - sanity-check:
          type: approval
          requires:
            - continuous-delivery

      - continuous-deployment:
          requires:
            - sanity-check
            - continuous-integration
            - continuous-delivery
